spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: ${USER_NAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# API 기본 경로
server:
  servlet:
    context-path: /api

# JWT 설정 추가
jwt:
  secret:
    key: TXlTdXBlclNlY3JldEtleQTXlTdXBlclNlY3JldEtleQTXlTdXBlclNlY3JldEtleQ==

# 로그 레벨
  logging:
  level:
    org:
      hibernate:
        SQL: DEBUG           # SQL 로그
        type:
          descriptor:
            sql:
              BasicBinder: TRACE   # 파라미터 바인딩 값 출력